name = "BCG+ Toasty Edition"
author = "jflec, Fummo"
version = "2.7.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52ffbfcfcb88c9cf4570bb9bda80c86d6c644a2d45cf84f027b87df927556743"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
