name = "BigChadGuys Plus Toasty Edition"
author = "Fummo"
version = "2.6.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e41bddec4e0cf788e5ba122be81b2724024188b526ea47966d55675849eba7e2"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
